In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import os
import sys


In [2]:
# Allow imports from parent directory 
# https://stackoverflow.com/questions/34478398/import-local-function-from-a-module-housed-in-another-directory-with-relative-im/35273613#35273613
#module_path = os.path.abspath(os.path.join(os.pardir))
module_path = 'C:\\Users\\agomez\\Dropbox\\Harvard\\LittleProjects\\StochasticPS\\programs\\'
if module_path not in sys.path:
    sys.path.append(module_path)
sys.path

['',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\python36.zip',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\DLLs',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.1-py3.6.egg',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg',
 'C:\\Users\\agomez\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\agomez\\.ipython',
 'C:\\Users\\agomez\\Dropbox\\Harv

In [3]:
import time
import datetime

import pandas as pd
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

import seaborn as sns

import itertools
import collections
import warnings
import IPython.display
import scipy.stats
import networkx as nx
from operator import itemgetter

plt.style.use('seaborn-white')
plt.rc('font', family='serif', serif='Times')
plt.rc('text', usetex=True)
plt.rc('xtick', labelsize=8)
plt.rc('ytick', labelsize=8)
plt.rc('axes', labelsize=9)


from sklearn.preprocessing import StandardScaler, RobustScaler, FunctionTransformer, PolynomialFeatures
from sklearn.decomposition import PCA, NMF
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

from numpy.random import exponential
from numpy.random import randint
from random import shuffle
from numpy.random import choice


In [4]:
import EComm_0001_complexities 

In [5]:
# Number of countries and products
Nc = 10
Np = 10


In [6]:
# Generating Cca and Ppa with the configuration model
# Two sets of countries

# Number of countries for set 1 and 2
Nc1 = np.int(np.floor(Nc/2.0))
Nc2 = np.int(np.ceil(Nc/2.0))
print(Nc1+Nc2==Nc)

# Names of countries
names1 = np.array(["A" + str(i).zfill(np.int(np.ceil(np.log10(Nc+1)))) for i in np.arange(1, Nc1+1)])
names2 = np.array(["B" + str(i).zfill(np.int(np.ceil(np.log10(Nc+1)))) for i in np.arange(1, Nc2+1)])
allcty_names = np.concatenate((names1, names2))
print(names1, names2, allcty_names)

True
['A01' 'A02' 'A03' 'A04' 'A05'] ['B01' 'B02' 'B03' 'B04' 'B05'] ['A01' 'A02' 'A03' 'A04' 'A05' 'B01' 'B02' 'B03' 'B04' 'B05']


In [7]:
# Generating Cca and Ppa with the configuration model
# Names of products
prod_names = np.array(["P" + str(i).zfill(np.int(np.ceil(np.log10(Np+1)))) for i in np.arange(1, Np+1)])
print(prod_names)

['P01' 'P02' 'P03' 'P04' 'P05' 'P06' 'P07' 'P08' 'P09' 'P10']


# Generate Cca

In [11]:
# The distribution of complexities will be exponential
cty_compl1 = np.ceil(exponential(scale=50.0, size=Nc1))
print(cty_compl1)
cty_compl2 = np.ceil(exponential(scale=50.0, size=Nc2))
print(cty_compl2)

# Creating the stubs for countries
cty_stubs1 = np.array([names1[country] for country in range(0,Nc1) for nodei in range(1,np.int(cty_compl1[country])+1)  ])
cty_stubs2 = np.array([names2[country] for country in range(0,Nc2) for nodei in range(1,np.int(cty_compl2[country])+1)  ])

cty_numstubs1 = len(cty_stubs1)
cty_numstubs2 = len(cty_stubs2)
print(cty_numstubs1,cty_numstubs2)


[  28.    4.   93.   86.  176.]
[ 113.   19.  182.   27.    6.]
387 347


In [12]:
max(cty_compl1)

176.0

In [14]:
# Names of capabilities
numcapabilities1 = np.int(max(cty_compl1))
numcapabilities2 = np.int(max(cty_compl2))
cap_names1 = np.array(["x" + str(i).zfill(np.int(np.ceil(np.log10(numcapabilities1+1)))) for i in np.arange(1, numcapabilities1+1)])
cap_names2 = np.array(["y" + str(i).zfill(np.int(np.ceil(np.log10(numcapabilities2+1)))) for i in np.arange(1, numcapabilities2+1)])
allcap_names = np.concatenate((cap_names1, cap_names2))
#print(cap_names1, cap_names2)


# The distribution of ubiquities of capabilities be uniform
cap_compl1 = np.array(randint(low=2, high=np.int(Nc1), size=len(cap_names1)))
print(cap_compl1)
cap_compl2 = np.array(randint(low=2, high=np.int(Nc2), size=len(cap_names2)))
print(cap_compl2)

# Creating the stubs for capabilities
cap_stubs1 = np.array([cap_names1[capability] for capability in range(0,len(cap_names1)) for nodei in range(1,np.int(cap_compl1[capability])+1)  ])
cap_stubs2 = np.array([cap_names2[capability] for capability in range(0,len(cap_names2)) for nodei in range(1,np.int(cap_compl2[capability])+1)  ])

cap_numstubs1 = len(cap_stubs1)
cap_numstubs2 = len(cap_stubs2)
print(cap_numstubs1,cap_numstubs2)



[4 4 2 4 3 4 3 4 3 4 2 2 4 2 2 4 3 2 4 2 3 4 3 2 4 3 4 4 2 2 4 4 3 2 2 2 4
 2 3 4 2 4 4 2 2 3 4 3 3 2 3 3 2 3 4 2 4 4 3 4 4 3 3 3 2 4 3 2 2 3 4 3 3 2
 3 2 4 3 2 2 4 4 2 4 3 3 3 3 2 3 4 4 2 2 4 2 2 4 4 2 4 3 2 4 4 2 4 2 3 4 4
 2 4 4 2 4 3 3 2 2 4 3 4 3 2 3 2 4 3 4 4 3 4 4 2 4 4 2 2 2 2 2 4 2 3 2 2 3
 2 4 4 2 4 3 2 2 3 4 2 3 3 2 3 2 3 3 3 3 3 4 2 3 3 2 2 3]
[3 2 3 4 2 3 3 3 2 4 4 3 4 4 2 4 2 2 4 2 3 3 3 4 4 4 4 4 2 2 2 2 4 3 4 4 4
 3 2 4 4 3 4 3 3 3 4 2 3 4 3 2 4 2 3 4 2 4 4 2 2 2 2 4 4 4 4 4 3 2 4 4 3 4
 2 3 3 3 2 4 2 4 2 4 3 4 3 3 4 2 3 3 2 2 2 4 4 3 3 3 2 4 4 3 4 3 2 3 2 3 2
 3 3 3 2 4 2 3 3 2 2 3 3 3 3 3 3 2 2 2 4 3 3 3 2 4 2 4 2 4 2 4 2 2 3 2 2 3
 3 2 2 2 3 4 4 4 4 4 3 4 3 4 4 2 3 3 4 4 3 3 4 3 2 4 4 4 3 4 4 3 2 3]
526 557


In [15]:
# Randomizing the stubs
shuffle(cty_stubs1)
shuffle(cty_stubs2)

shuffle(cap_stubs1)
shuffle(cap_stubs2)


In [16]:
min(len(cty_stubs1),len(cap_stubs1))

387

In [17]:
bipartite_longdf1 = np.array([[cty_stubs1[i], cap_stubs1[i]] for i in range(0, min(len(cty_stubs1),len(cap_stubs1)))])
bipartite_longdf2 = np.array([[cty_stubs2[i], cap_stubs2[i]] for i in range(0, min(len(cty_stubs2),len(cap_stubs2)))])

# Creating off-diagonal elements
ncross = 10
cty_subsampl = np.array(choice(allcty_names, size=ncross))
cap_subsampl = np.array(choice(allcap_names, size=ncross))
offdiag_longdf = np.array([[cty_subsampl[i], cap_subsampl[i]] for i in range(0, ncross)])



In [18]:
bipartite_long = np.concatenate((bipartite_longdf1, bipartite_longdf2,offdiag_longdf), axis=0)
print(bipartite_long.shape)
bipartite_long = np.unique(bipartite_long, axis=0)
print(bipartite_long.shape)

bipartite_longdfall = pd.DataFrame(bipartite_long, columns=['country_code', 'capability_code'])
bipartite_longdfall['Edge'] = 1

(744, 2)
(572, 2)


In [19]:
Cca_df_wide = bipartite_longdfall.pivot(index='country_code', columns='capability_code', values='Edge').fillna(0.0)
Cca_df_wide

capability_code  x001  x002  x003  x004  x005  x006  x007  x008  x009  x010  \
country_code                                                                  
A01               0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   
A02               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
A03               1.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   1.0   0.0   
A04               1.0   1.0   1.0   0.0   0.0   1.0   1.0   1.0   0.0   1.0   
A05               1.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   1.0   
B01               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
B02               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
B03               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
B04               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
B05               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

capability_code  ...   y172  y173  y174  y175  y176  y177  y178  y179  y180  \
country_code     ...                                                          
A01              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
A02              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
A03              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
A04              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
A05              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
B01              ...    0.0   1.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   
B02              ...    1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
B03              ...    1.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
B04              ...    0.0   1.0   0.0   1.0   1.0   0.0   0.0   1.0   0.0   
B05              ...    0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   

capability_code  y182  
country_code           
A01               0.0  
A02               0.0  
A03               0.0  
A04               0.0  
A05               0.0  
B01               0.0  
B02               0.0  
B03               1.0  
B04               0.0  
B05               0.0  

[10 rows x 343 columns]

In [20]:
cty_complexities = Cca_df_wide.sum(axis=1)
cty_complexities

country_code
A01     26.0
A02      4.0
A03     79.0
A04     70.0
A05    121.0
B01     91.0
B02     17.0
B03    131.0
B04     26.0
B05      7.0
dtype: float64

In [21]:
maximumcomplexity = np.max(cty_complexities)
maximumcomplexity

131.0

# Generate Ppa

In [22]:
(cty_complexities.values, cty_complexities.index)

(array([  26.,    4.,   79.,   70.,  121.,   91.,   17.,  131.,   26.,    7.]),
 Index(['A01', 'A02', 'A03', 'A04', 'A05', 'B01', 'B02', 'B03', 'B04', 'B05'], dtype='object', name='country_code'))

In [23]:
sorted_cty_complexities = cty_complexities[np.argsort(cty_complexities.values)]
sorted_cty_complexities

country_code
A02      4.0
B05      7.0
B02     17.0
A01     26.0
B04     26.0
A04     70.0
A03     79.0
B01     91.0
A05    121.0
B03    131.0
dtype: float64

In [32]:
sorted_cty_complexities.index[1]

'A05'

In [33]:
Cca_df_wide.loc[sorted_cty_complexities.index[1]]

capability_code
x001    0.0
x003    0.0
x004    0.0
x005    0.0
x006    0.0
x007    0.0
x008    0.0
x009    0.0
x010    0.0
x011    0.0
x013    1.0
x014    0.0
x015    0.0
x017    0.0
x018    0.0
x019    0.0
x022    0.0
x023    0.0
x024    0.0
x025    0.0
x026    0.0
x027    0.0
x029    0.0
x030    0.0
x031    0.0
x032    0.0
x033    0.0
x035    0.0
x037    0.0
x038    0.0
       ... 
y387    0.0
y388    0.0
y389    0.0
y390    0.0
y391    0.0
y392    0.0
y394    0.0
y395    0.0
y396    0.0
y397    0.0
y399    0.0
y400    0.0
y401    0.0
y405    0.0
y406    0.0
y407    0.0
y408    0.0
y409    0.0
y410    0.0
y412    0.0
y414    0.0
y415    0.0
y417    0.0
y418    0.0
y420    0.0
y423    0.0
y424    0.0
y426    0.0
y427    0.0
y429    0.0
Name: A05, Length: 563, dtype: float64

In [ ]:
j = 1
ctyindex_j = sorted_cty_complexities.index[j]
[ i for i, x in enumerate() if x == value ]

In [18]:
# We will use the same stubs from the countries, so that a capability that is own by several countries
# is a capability that is easy to acquire, and therefore, it will also be a capability common as a
# requirement for products.
allcap_stubs = np.concatenate((cap_stubs1, cap_stubs2))
len(allcap_stubs)/Np # capabilities required by product

263.9

In [19]:
(len(allcap_names),len(allcap_stubs))

(882, 2639)

In [20]:
# The distribution of product complexities will be uniform
prod_compl = np.ceil(randint(low=1, high=np.int(np.log(len(allcap_stubs))), size=Np))
print(prod_compl)

# Creating the stubs for products
prod_stubs = np.array([prod_names[product] for product in range(0,Np) for nodei in range(1,np.int(prod_compl[product])+1)  ])

prod_numstubs = len(prod_stubs)
print(prod_numstubs)


[ 3.  3.  5.  5.  2.  2.  3.  5.  6.  4.]
38


In [21]:
# Randomizing the stubs
shuffle(prod_stubs)

shuffle(allcap_stubs)


In [22]:
min(len(prod_stubs),len(allcap_stubs))

38

In [23]:
bipartitePpa_longdf = np.array([[prod_stubs[i], allcap_stubs[i]] for i in range(0, min(len(prod_stubs),len(allcap_stubs)))])
bipartitePpa_longdf.shape

(38, 2)

In [24]:
bipartitePpa_longdf = np.unique(bipartitePpa_longdf, axis=0)
print(bipartitePpa_longdf.shape)

bipartitePpa_longdfall = pd.DataFrame(bipartitePpa_longdf, columns=['product_code', 'capability_code'])
bipartitePpa_longdfall['Edge'] = 1

(38, 2)


In [25]:
Ppa_df_wide = bipartitePpa_longdfall.pivot(columns='capability_code', index='product_code', values='Edge').fillna(0.0)
Ppa_df_wide

capability_code  x011  x162  x177  x231  x251  x265  x298  x300  x341  x357  \
product_code                                                                  
P01               0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
P02               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P03               0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
P04               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P05               0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
P06               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P07               1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P08               0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
P09               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   
P10               0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   

capability_code  ...   y262  y295  y300  y305  y327  y387  y414  y415  y421  \
product_code     ...                                                          
P01              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P02              ...    0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   
P03              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P04              ...    1.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
P05              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P06              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P07              ...    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
P08              ...    0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   
P09              ...    0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
P10              ...    0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   

capability_code  y437  
product_code           
P01               0.0  
P02               0.0  
P03               1.0  
P04               0.0  
P05               0.0  
P06               0.0  
P07               0.0  
P08               0.0  
P09               0.0  
P10               0.0  

[10 rows x 38 columns]

In [ ]:
617 495 2068
oct 11 at 10:30

In [26]:
Ppa_df_wide.sum(axis=1)

product_code
P01    3.0
P02    3.0
P03    5.0
P04    5.0
P05    2.0
P06    2.0
P07    3.0
P08    5.0
P09    6.0
P10    4.0
dtype: float64

# Getting all info together

In [27]:
(Cca_df_wide.shape, Ppa_df_wide.shape)

((10, 691), (10, 38))

In [28]:
finalcaps_names = np.sort(np.array(list(set(Cca_df_wide.columns.values) & set(Ppa_df_wide.columns.values))))

In [29]:
finalcaps_names

array(['x011', 'x162', 'x177', 'x231', 'x251', 'x265', 'x298', 'x341',
       'x357', 'x360', 'x376', 'x382', 'x392', 'x425', 'y017', 'y023',
       'y080', 'y110', 'y116', 'y143', 'y176', 'y199', 'y224', 'y233',
       'y243', 'y255', 'y262', 'y300', 'y305', 'y327', 'y414', 'y421',
       'y437'],
      dtype='<U4')

In [30]:
Cca_final = Cca_df_wide[finalcaps_names]
Ppa_final = Ppa_df_wide[finalcaps_names]

In [31]:
Cca_final = Cca_final.loc[Cca_final.sum(axis=1)>0]
Ppa_final = Ppa_final.loc[Ppa_final.sum(axis=1)>0]

In [32]:
Cca_final.sum(axis=1)

country_code
A01    12.0
A02     3.0
A03     1.0
A04     1.0
B02     1.0
B03    11.0
B04     3.0
B05     9.0
dtype: float64

In [33]:
asdf = np.array(Cca_final)

In [34]:
asdf.flatten()

array([ 1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0

In [35]:
(Cca_final.shape, Ppa_final.shape)

((8, 33), (10, 33))

In [36]:
EComm_0001_complexities.ProductionMatrix(np.array(Cca_final), np.array(Ppa_final).T, 1)

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]])

In [37]:
[[np.int(EComm_0001_complexities.Leontief(c, p)) for p in np.array(Ppa_final)] for c in np.array(Cca_final)]

[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]

In [38]:
if(True):
    for cindex, c in enumerate(np.array(Cca_final)):
        for pindex, p in enumerate(np.array(Ppa_final)):
            print(c)
            print(p)
            print("cp {}-{} = {}".format(cindex, pindex, EComm_0001_complexities.Leontief(c, p)))

[ 1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
cp 0-0 = 0.0
[ 1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
cp 0-1 = 1.0
[ 1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
cp 0-2 = 0.0
[ 1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.